import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { LoginProvider } from "@/libs/ui/providers/LoginContext";
import { AuthProvider } from '@/libs/ui/providers/AuthContext';
import { Sidebar } from "@/libs/ui/component/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Virtual Classroom",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <LoginProvider>
    <html lang="en">
      <body className={inter.className}>
        <Sidebar />
        <AuthProvider>
          <main className='mx-1 mt-0 sm:ml-[200px] sm:mt-0'>{children}</main>
        </AuthProvider>
      </body>
    </html>
    </LoginProvider>
  );
}
